version: '3.8'

services:
  # Serviço do banco de dados MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Serviço do aplicativo Flask
  flask:
    env_file:
      - .env
    build:
      context: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+mysqlconnector://flask_user:flask_password@mysql_db:3306/flask_db
    depends_on:
      - mysql

# Volume para persistência de dados do MySQL
volumes:
  db_data:
